// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmS-AmMHknyROkNaQX5k8ZvYNwTIkmcUk',
    appId: '1:191726283967:web:5d4a9243b5b4fd0e32ea0a',
    messagingSenderId: '191726283967',
    projectId: 'ititask-f8f18',
    authDomain: 'ititask-f8f18.firebaseapp.com',
    storageBucket: 'ititask-f8f18.firebasestorage.app',
    measurementId: 'G-MN29XGVD5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4UYDXnXMYIxOs4lGOrAeb7gi6r-gKA4',
    appId: '1:191726283967:android:86a3b8b58c1564a532ea0a',
    messagingSenderId: '191726283967',
    projectId: 'ititask-f8f18',
    storageBucket: 'ititask-f8f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGrNltxvk8pGJFSDH2cVNIwHZKSCV9oyA',
    appId: '1:191726283967:ios:caa2629543bf682632ea0a',
    messagingSenderId: '191726283967',
    projectId: 'ititask-f8f18',
    storageBucket: 'ititask-f8f18.firebasestorage.app',
    iosBundleId: 'com.example.ititask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGrNltxvk8pGJFSDH2cVNIwHZKSCV9oyA',
    appId: '1:191726283967:ios:caa2629543bf682632ea0a',
    messagingSenderId: '191726283967',
    projectId: 'ititask-f8f18',
    storageBucket: 'ititask-f8f18.firebasestorage.app',
    iosBundleId: 'com.example.ititask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmS-AmMHknyROkNaQX5k8ZvYNwTIkmcUk',
    appId: '1:191726283967:web:af78442cff5a998932ea0a',
    messagingSenderId: '191726283967',
    projectId: 'ititask-f8f18',
    authDomain: 'ititask-f8f18.firebaseapp.com',
    storageBucket: 'ititask-f8f18.firebasestorage.app',
    measurementId: 'G-KQ4EZ8MWCM',
  );
}
